{
    "name": "G2P: Badge Tags-Input Field",
    "category": "G2P",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "Other OSI approved licence",
    "development_status": "Alpha",
    "depends": ["base"],
    "assets": {
        "web.assets_backend": [
            "g2p_badge_input_field/static/lib/tagsinput/bootstrap-tagsinput.css",
            "g2p_badge_input_field/static/lib/tagsinput/bootstrap-tagsinput.js",
            "g2p_badge_input_field/static/src/scss/char_field_widget.scss",
            "g2p_badge_input_field/static/src/js/char_field_widget.js",
            "g2p_badge_input_field/static/src/xml/char_field_widget.xml",
        ],
    },
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
